### PR TITLE
Common scalafmt config

### PR DESCRIPTION
**Pull request by armanbilge**
Based on https://github.com/gemini-hlsw/sbt-lucuma/pull/138. Fixes https://github.com/gemini-hlsw/sbt-lucuma/issues/9.

Here I've created a `LucumaScalafmtPlugin`. It works similar to sbt-gh-actions:
1. Use `lucumaScalafmtGenerate` to generate the common config file.
2. Add `include ".scalafmt-common.conf"` to `.scalafmt.conf` to apply it to a project.
3. In CI `lucumaScalafmtCheck` is used to check that it is up-to-date with the config distributed with the plugin.

I propose that we incubate this idea in sbt-lucuma, and if it works well I'll upstream it into sbt-typelevel.

### CODE REVIEW

**Comment by swalker2m** [comment]
> In CI `lucumaScalafmtCheck` is used to check that it is up-to-date with the config distributed with the plugin.

(`scalafmt` skeptic here) I just want to confirm that it remains optional per-project?

**Comment by armanbilge** [comment]
You'll get stuck with an unused `.scalafmt-common.conf` file in your repo, but other than that scalafmt is easy disabled like this:
```
project.includePaths = [] # disables formatting
```

I can make the CI check configurable if an unused `.scalafmt-common.conf` is going to be annoying.

**Comment by swalker2m** [comment]
> I can make the CI check configurable if an unused .scalafmt-common.conf is going to be annoying.

No, it sounds like it should be fine.

**Comment by armanbilge** [comment]
Not intentionally. Better review/merge separately.

**Review by cquiroz — APPROVED** [review]
LGTM. I love the idea of moving the ScalafmtPlugin upstream

**Pull request merged**
