### PR TITLE
Default CI to JDK 17 only

### PR DESCRIPTION
**Pull request by armanbilge**
This only affects the app plugin.

### CODE REVIEW

**Review by cquiroz — APPROVED** [review]
Should libs also be 17 only?

**Comment by armanbilge** [comment]
> Should libs also be 17 only?

Good point. Some of your libs you want eventually upstream to Typelevel/OSS right? Those should probably continue building for 8 and 17. But if there's less of those than internal libs, then maybe JDK 17 should be the default for everything and we can handle those special cases.

**Comment by armanbilge** [comment]
Ok, I'll switch everything to 17 only and we can special-case anything you may want to upstream in the future.

**Comment by armanbilge** [comment]
Looks like you'll have to update your settings again, since we dropped the JDK 8 job 😅

**Review by tpolecat — APPROVED** [review]
Seems fine as a default.

**Pull request merged**
